spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: UTC
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/loja
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver


