spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      jdbc:
        time_zone: UTC
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5433/Loja
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always

