spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5433/Loja
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

